# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-24 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('q_type', models.CharField(max_length=8)),
                ('answer', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
    ]
